### Retrieve all business partners  
GET http://localhost:4004/odata/v4/Procurement/businesspartner HTTP/1.1

### Retrieve a single address record by its key  
GET http://localhost:4004/odata/v4/Procurement/address/4aad1e3b-a70a-4a26-9521-5990f3519

### Retrieve purchase order items with expanded parent key and business partner details  
GET http://localhost:4004/odata/v4/Procurement/poitems?$expand=parent_key($expand=partner_guid)

### Retrieve business partners filtered by role (bp_role = 1)  
GET http://localhost:4004/odata/v4/Procurement/businesspartner?$filter=bp_role eq 1  

### Retrieve business partners sorted by company name (ascending order)  
GET http://localhost:4004/odata/v4/Procurement/businesspartner?$orderby=company_name asc 

### Count the total number of business partners  
GET http://localhost:4004/odata/v4/Procurement/businesspartner/$count  


### CRUD Operations  

### Create a new business partner  
POST http://localhost:4004/odata/v4/Procurement/businesspartner  HTTP/1.1
Content-Type: application/json

{
   "node_key": "946fa5e5-e99f-456a-80d0-6d9de58caf6c",
      "bp_role": 1,
      "email_address": "infopost1@test.ca",
      "phone_number": 6049876123,
      "fax_number": 6049876345,
      "web_address": "www.testpost1.ca",
      "bp_id": 1212,
      "company_name": "Post1 Ca"
}


### PUT - Update an existing business partner
PUT http://localhost:4004/odata/v4/Procurement/businesspartner/946fa5e5-e99f-456a-80d0-6d9de58caf6c  HTTP/1.1
Content-Type: application/json

{
    "email_address": "put@test.ca",
  "phone_number": 6049876000
}


### Create another new business partner  
POST http://localhost:4004/odata/v4/Procurement/businesspartner  HTTP/1.1
Content-Type: application/json

{
   "node_key": "cb32b7f4-2055-4547-a44a-8e84cfc0beec",
      "bp_role": 1,
      "email_address": "info@testpost2.ca",
      "phone_number": 6049876111,
      "fax_number": 6049876222,
      "web_address": "www.posttest2.ca",
      "bp_id": 1213,
      "company_name": "Post2 Company"
}


### PATCH - Partially update an existing business partner (only specified fields) 
PATCH  http://localhost:4004/odata/v4/Procurement/businesspartner/cb32b7f4-2055-4547-a44a-8e84cfc0beec  HTTP/1.1
Content-Type: application/json

{
    "email_address": "patchcompany@test.ca",
  "phone_number": 6049876111
}


### Delete an existing business partner  
DELETE http://localhost:4004/odata/v4/Procurement/businesspartner/cb32b7f4-2055-4547-a44a-8e84cfc0beec HTTP/1.1


### Validate custom aspect for gender, email and phone number
POST http://localhost:4004/odata/v4/Procurement/employee HTTP/1.1
Content-Type: application/json

 {
      "firstName": "John",
      "lastName": "Smith",
      "gender": "H",
      "phoneNumber": "5149631000",
      "email": "js@gmail.com",
      "currency": "CAD",
      "salaryAmount": "45000"
    }